name: CI

on: push

env:
  NODE_ENV: development

jobs:
  core:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - id: build
        run: npm install --legacy-peer-deps

      - id: build-core
        run: |
          npm install --legacy-peer-deps
          npm run build -- --ci
          tar -cf ionic-core.tar node_modules dist components css hydrate loader
        working-directory: core

      - id: test-core-clean-build
        name: Checking clean build
        run: git diff --exit-code
        working-directory: core

      - id: test-core-lint
        run: npm run lint
        working-directory: core

      - uses: actions/upload-artifact@v2
        with:
          name: ionic-core
          path: core/ionic-core.tar

  test:
    runs-on: ubuntu-latest
    needs: core

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - uses: actions/download-artifact@v2
        with:
          name: ionic-core
          path: core

      - run: |
          tar -xf ionic-core.tar
          npm link
        working-directory: core

      - id: test-core-e2e
        run: npm run test.e2e -- --ci --no-build
        working-directory: core

      - id: test-core-spec
        run: npm run test.spec -- --ci
        working-directory: core

      - id: puppeteer-dependencies
        name: Install Puppeteer with Chromium
        run: npm i puppeteer

      - id: test-core-screenshot
        if: ${{ github.ref != 'refs/heads/main' }}
        name: Run Screenshot
        run: npx stencil test --e2e --screenshot --screenshot-connector=scripts/screenshot/ci.js --ci --no-build || true
        working-directory: core

      - id: test-core-screenshot-master
        if: ${{ github.ref == 'refs/heads/main' }}
        name: Run Screenshot
        run: npx stencil test --e2e --screenshot --screenshot-connector=scripts/screenshot/ci.js --ci --update-screenshot --no-build || true
        working-directory: core

  angular:
    runs-on: ubuntu-latest
    needs: core

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - uses: actions/download-artifact@v2
        with:
          name: ionic-core
          path: core

      - run: |
          tar -xf ionic-core.tar
          npm link
        working-directory: core

      - id: build-angular
        run: |
          npm install --legacy-peer-deps
          npm link @ionic/core
          npm run build
        working-directory: angular

      - id: test-angular-lint
        run: npm run lint
        working-directory: angular

      - id: build-angular-server
        run: |
          npm install --legacy-peer-deps
          npm run build.prod
        working-directory: packages/angular-server

      - id: test-angular-e2e
        run: |
          npm install --legacy-peer-deps
          npm run test
        working-directory: angular/test/test-app

  react:
    runs-on: ubuntu-latest
    needs: core

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - uses: actions/download-artifact@v2
        with:
          name: ionic-core
          path: core

      - run: |
          tar -xf ionic-core.tar
          npm link
        working-directory: core

      - id: build-react
        run: |
          npm install --legacy-peer-deps
          npm link @ionic/core
          npm run build
        working-directory: packages/react

      - run: npm link
        working-directory: packages/react

      - id: build-react-router
        run: |
          npm install --legacy-peer-deps
          npm link @ionic/core
          npm link @ionic/react
          npm run build
        working-directory: packages/react-router

      - id: test-react-lint
        run: npm run lint
        working-directory: packages/react

      - id: test-react-router-lint
        run: npm run lint
        working-directory: packages/react-router

      - id: test-react-spec
        run: npm run test.spec
        working-directory: packages/react

      - id: test-react-router-spec
        run: npm run test.spec
        working-directory: packages/react-router

      - id: install-react-test-app
        run: npm install
        env:
          CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/packages/react-router/test-app
        working-directory: packages/react-router/test-app

      - id: test-react-e2e
        run: |
          npm run sync
          npm run e2e
        env:
          CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/packages/react-router/test-app
        working-directory: packages/react-router/test-app

  vue:
    runs-on: ubuntu-latest
    needs: core

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - uses: actions/download-artifact@v2
        with:
          name: ionic-core
          path: core

      - run: |
          tar -xf ionic-core.tar
          npm link
        working-directory: core

      - id: build-vue
        run: |
          npm install
          npm link @ionic/core
          npm run build
        working-directory: packages/vue

      - run: npm link
        working-directory: packages/vue

      - id: build-vue-router
        run: |
          npm install
          npm link @ionic/vue
          npm run build
        working-directory: packages/vue-router

      - id: test-vue-lint
        run: npm run lint
        working-directory: packages/vue

      - id: test-vue-router-lint
        run: npm run lint
        working-directory: packages/vue-router

      - id: test-vue-router-spec
        run: npm run test.spec
        working-directory: packages/vue-router

      - id: install-vue-test-app
        run: npm install
        env:
          CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/packages/vue/test-app
        working-directory: packages/vue/test-app

      - id: test-vue-spec-and-e2e
        run: |
          npm run sync
          npm run test:unit
          npm run test:e2e
        env:
          CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/packages/vue/test-app
        working-directory: packages/vue/test-app
